# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
- name: Cache
  uses: actions/cache@v1.0.2
  with:
    # A directory to store and save the cache
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
    - name: Setup Node.js environment
  uses: actions/setup-node@v1.1.0
  with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
    version: # optional, default is 10.x
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
    registry-url: # optional
    # Optional scope for authenticating against scoped registries
    scope: # optional
    - name: Upload a Build Artifact
  uses: actions/upload-artifact@v1.0.0
  with:
    # Artifact name
    name: 
    # Directory containing files to upload
    path: 
    - name: Setup Java JDK
  uses: actions/setup-java@v1.0.0
  with:
    # The JDK version to make available on the path. Takes a whole or semver Jdk version, or 1.x syntax (e.g. 1.8 => Jdk 8.x)
    version: 
    # The architecture (x86, x64) of the JDK.
    architecture: # default is x64
    # Path to where the compressed JDK is located. The path could be in your source repository or a local path on the agent.
    jdkFile: # optional
    - name: Download a Build Artifact
  uses: actions/download-artifact@v1.0.0
  with:
    # Artifact name
    name: 
    # Destination path
    path: # optional
